<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends EntityRepository {

	public function getUltimasNoticias() {
		$qb = $this->createQueryBuilder( 'n' );

		$qb->orderBy( 'n.creado', ' DESC' )
		   ->setMaxResults( 10 );

		return $qb->getQuery()->getResult();
	}
}
