rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ubicacion:
    resource: "@UbicacionBundle/Resources/config/routing.yml"
    prefix:   /ubicacion

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

